{
  callPackage,
  lib,
  modulesPath,
  nixos-modules,
  nixosOptionsDoc,
  perl,
  pkgs,
  python3,
  stdenv,
  texlive,
  version,
  ...
}:
stdenv.mkDerivation (finalAttrs: {
  name = "NGIpkgs-Manuals";
  inherit version;
  src =
    with lib.fileset;
    toSource {
      root = ../.;
      fileset = intersection (gitTracked ../.) (unions [
        (fileFilter (
          file:
          lib.any file.hasExt [
            "md"
            "nix"
          ]
        ) ../.)
        ./Makefile
        ./_ext
        ./_redirects
        ./_static
        ./_templates
        ./conf.py
        ./favicon.png
        ./netlify.toml
        ./robots.txt
        ../projects
      ]);
    };

  nativeBuildInputs = [
    finalAttrs.passthru.pythonPackages
    finalAttrs.passthru.texPackages
    perl
  ];

  patchPhase = ''
    runHook prePatch
    substituteInPlace manuals/index.md \
      --replace-fail '@MANUALS_VERSION@' "${version}"
    runHook postPatch
  '';

  buildPhase = ''
    runHook preBuild
    pushd manuals
    make html
    make singlehtml
    make latexpdf
    popd
    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall
    pushd manuals
    mkdir $out
    cp -R build/html $out/
    cp -R build/singlehtml $out/
    cp build/latex/NGIpkgs_Manuals.pdf $out/
    cp netlify.toml $out/
    popd
    runHook postInstall
  '';

  passthru = {
    pythonPackages = python3.withPackages (
      pyPkgs: with pyPkgs; [
        linkify-it-py
        myst-parser
        sphinx
        sphinx-book-theme
        sphinx-copybutton
        sphinx-design
        sphinx-notfound-page
        sphinx-sitemap
      ]
    );

    # Explanation: those TeX packages are dependencies to provision
    # for the build/latex/*.{tex,sty} files generated by sphinx,
    # ./tex-env.nix has itself been generated with:
    # nix run github:rgri/tex2nix -- build/latex/*.{tex,sty}
    texPackages = (
      callPackage ./tex-env.nix {
        extraTexPackages = {
          inherit (texlive)
            latexmk
            collection-fontsrecommended
            collection-latexrecommended
            collection-luatex
            gnu-freefont # For FreeSerif.otf
            ;
        };
      }
    );

    optionsDoc = nixosOptionsDoc {
      options =
        lib.flip builtins.removeAttrs [ "_module" ]
          (lib.evalModules {
            class = "nixos";
            specialArgs = {
              inherit pkgs modulesPath;
            };
            modules = [
              {
                config = {
                  # Explanation: do not check anything
                  # because NixOS options are not included.
                  # See also comment in NixOS' `noCheckForDocsModule`.
                  _module.check = false;
                };
                imports = lib.attrValues nixos-modules.services ++ lib.attrValues nixos-modules.programs;
              }
            ];
          }).options;
    };
  };
})
