{
  callPackage,
  fetchurl,
  gnused,
  imagemagick,
  lib,
  manuals,
  modulesPath,
  nixos-modules,
  nixosOptionsDoc,
  perl,
  pkgs,
  python3,
  stdenv,
  texlive,
  version,
  writeText,
  ...
}:
let
  common = stdenv.mkDerivation (finalAttrs: {
    pname = "NGIpkgs-Manuals-${finalAttrs.passthru.format}";
    inherit version;
    src =
      with lib.fileset;
      toSource {
        root = ../.;
        fileset = intersection (gitTracked ../.) (unions [
          (fileFilter (
            file:
            lib.any file.hasExt [
              "md"
              "nix"
              "svg"
            ]
          ) ../.)
          ./Makefile
          ./_ext
          ./_redirects
          ./_static
          ./_templates
          ./conf.py
          ./favicon.png
          ./netlify.toml
          ./robots.txt
          ../projects
        ]);
      };

    nativeBuildInputs = [
      finalAttrs.passthru.pythonPackages
      gnused
      perl
      imagemagick
    ];

    patchPhase = ''
      runHook prePatch
      ln -sf ${manuals.optionsMyST} manuals/options.md
      magick ${finalAttrs.passthru.logo} manuals/_static/_img/nix.pdf
      substituteInPlace manuals/index.md \
        --replace-fail '@MANUALS_VERSION@' "${version}"
      runHook postPatch
    '';

    buildPhase = ''
      runHook preBuild
      make -C manuals ${finalAttrs.passthru.format}
      runHook postBuild
    '';

    passthru = {
      logo = fetchurl {
        url = "https://brand.nixos.org/logos/nixos-logomark-default-gradient-minimal.svg";
        hash = "sha256-YrOle9qo0G92vvCjy9FAkyNOdyAz1DR+xoc+/CpK0yk=";
      };
      pythonPackages = python3.withPackages (
        pyPkgs: with pyPkgs; [
          linkify-it-py
          myst-parser
          sphinx
          sphinx-book-theme
          sphinx-copybutton
          sphinx-design
          sphinx-notfound-page
          sphinx-sitemap
        ]
      );
    };
  });
in
# Explanation: split the different formats
# in different derivations instead of different outputs
# in order to only use `nix build -f. manuals.singlehtml`
# as a `.git/hooks/pre-push` check.
lib.recurseIntoAttrs {
  html = common.overrideAttrs (previousAttrs: {
    installPhase = ''
      runHook preInstall
      cp -R manuals/build/html $out/
      cp manuals/netlify.toml $out/
      runHook postInstall
    '';
    passthru = previousAttrs.passthru or { } // {
      format = "html";
    };
  });

  latexpdf = common.overrideAttrs (
    finalAttrs: previousAttrs: {
      nativeBuildInputs = previousAttrs.nativeBuildInputs or [ ] ++ [
        finalAttrs.passthru.texPackages
      ];
      installPhase = ''
        runHook preInstall
        install -Dm444 manuals/build/latex/NGIpkgs_Manuals.pdf $out/NGIpkgs_Manuals.pdf
        runHook postInstall
      '';
      passthru = previousAttrs.passthru or { } // {
        format = "latexpdf";
        # Explanation: those TeX packages are dependencies to provision
        # for the build/latex/*.{tex,sty} files generated by sphinx,
        # ./tex-env.nix has itself been generated with:
        # nix run github:rgri/tex2nix -- build/latex/*.{tex,sty}
        texPackages = (
          callPackage ./tex-env.nix {
            extraTexPackages = {
              inherit (texlive)
                latexmk
                collection-fontsrecommended
                collection-latexrecommended
                collection-luatex
                gnu-freefont # For FreeSerif.otf
                ;
            };
          }
        );
      };
    }
  );

  singlehtml = common.overrideAttrs (previousAttrs: {
    passthru = previousAttrs.passthru or { } // {
      format = "singlehtml";
    };
    installPhase = ''
      runHook preInstall
      cp -R manuals/build/singlehtml $out/
      cp manuals/netlify.toml $out/
      runHook postInstall
    '';
  });

  # Explanation: NixOS' `nixos-render-docs options commonmark`
  # generates a markdown that is not compatible with MyST,
  # and assumes it's only use in the context of NixOS.
  # This generates a valid MyST syntax from `manuals.optionsDoc.optionsNix`.
  optionsMyST =
    let
      fixContent =
        text:
        lib.replaceStrings
          [
            "(#opt-"
            "{.note}"
            "{.warning}"
            "{var}"
          ]
          [
            "(https://nixos.org/manual/nixos/unstable/#opt-"
            "{note}"
            "{warning}"
            "{option}"
          ]
          (lib.removeSuffix "\n" text);
      renderCode =
        arg:
        if lib.typeOf arg == "string" then
          fixContent arg
        else
          let
            text = fixContent arg.text;
          in
          if arg._type == "literalExpression" then
            if lib.match ".*\n.*" text == null then
              ''`${lib.replaceStrings [ "`" ] [ "\\`" ] text}`''
            else
              ''

                ```
                ${lib.replaceStrings [ "```" ] [ "\\`\\`\\`" ] text}
                ```
              ''
          else if arg._type == "literalMD" then
            text
          else
            # FixMe(completeness): unsupported arg._type
            assert (lib.trace arg._type false);
            "";
      renderId = lib.concatMapStringsSep "-" (
        part:
        lib.concatStrings (
          lib.map (
            c: if "0" <= c && c <= "9" || "a" <= c && c <= "z" || "A" <= c && c <= "Z" then c else "_"
          ) (lib.stringToCharacters part)
        )
      );
    in
    writeText "options.md" (
      ''
        {#User_What_is_the_tree_of_options}
        # What is the tree of options?

        The following tree of options is provided by importing:
        - `inputs.NGIpkgs.nixosModules.programs`
        - `inputs.NGIpkgs.nixosModules.services`

      ''
      + lib.concatStringsSep "\n\n" (
        lib.concatAttrValues (
          lib.mapAttrs (optName: opt: [
            (
              ''
                {#option-${renderId opt.loc}}
                ## ${lib.escapeXML optName}
              ''
              + lib.optionalString opt.readOnly ''
                - ReadOnly: ${toString opt.readOnly}
              ''
              + ''
                - Type: `${opt.type}`
                - Description: ${renderCode opt.description}
              ''
              + lib.optionalString (opt ? "default") ''
                - Default: ${renderCode opt.default}
              ''
              + lib.optionalString (opt ? "example") ''
                - Example: ${renderCode opt.example}
              ''
            )
          ]) manuals.optionsDoc.optionsNix
        )
      )
    );

  optionsDoc = nixosOptionsDoc {
    revision = version;
    options =
      lib.flip lib.removeAttrs [ "_module" ]
        (lib.evalModules {
          class = "nixos";
          specialArgs = {
            inherit pkgs modulesPath;
          };
          modules = [
            {
              config = {
                # Explanation: do not check anything
                # because NixOS options are not included.
                # See also comment in NixOS' `noCheckForDocsModule`.
                _module.check = false;
              };
              imports = lib.attrValues nixos-modules.programs ++ lib.attrValues nixos-modules.services;
            }
          ];
        }).options;
  };
}
