name: CI

on:
  push:

jobs:
  packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v21
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix build -L --no-link .#weblate
