name: "Task: Triage project"
description: Collect information about an NGI project
title: "<PROJECT NAME>: Triage metadata"
labels: ["good first issue", "triage"]
projects: ["Nix@NGI"]
body:
  - type: markdown
    id: notes_tasks
    attributes:
      value: |
        > [!IMPORTANT]
        > After triaging the project, make sure to open sub-tasks for each deliverable under the parent issue.
  - type: textarea
    id: instructions
    attributes:
      label: Instructions
      value: |
        Collect relevant information about this project by following the instructions in the [contributing guide](https://github.com/ngi-nix/ngipkgs/blob/main/CONTRIBUTING.md#triaging-an-ngi-application) and put the metadata in the parent issue: `NGI PROJECT: <PROJECT_NAME>`.
    validations:
      required: true
  - type: markdown
    id: notes_markdown
    attributes:
      value: |
        ## Additional information

        In the following text area, put:

        - Any information that can help with the task
        - Things that need to be done after the project has been triaged

        If no such thing exists, you can leave it empty.
  - type: textarea
    id: notes
    attributes:
      label: Notes
      placeholder: |
        - Issue #123 has some data on the project
        - Previous packaging attempt has been done in https://...
        - After the project is triaged, close #42
