# This is a pyproject.toml file deliberately written for packaging Weblate with poetry2nix.
# It doesn't have anything in common with upstream's pyproject.toml, except for
# the the version bounds that were manually translated to poetry syntax.

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools", "wheel", "translate-toolkit"]  # PEP 508 specifications.
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "weblate"
version = "5.6.2"
description = ""
authors = [{name = "Michal Čihař", email = "michal@weblate.org"}]
license = "GPLv3+"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
aeidon = ">=1.14.1,<1.16"
ahocorasick-rs = ">=0.20.0,<0.23.0"
borgbackup = ">=1.2.5,<1.3"
celery = { extras = ["redis"], version = ">=5.4.0,<5.5" }
certifi = ">=2023.7.22"
charset-normalizer = ">=2.0.12,<4.0"
crispy-bootstrap3 = "==2024.1"
cryptography = ">=42.0.2"
cssselect = ">=1.2,<1.3"
Cython = ">=3.0.0,<3.1"
diff-match-patch = "==20230430"
django-appconf = ">=1.0.3,<1.1"
django-celery-beat = ">=2.6.0,<2.7"
django-compressor = ">=4.4,<5"
django-cors-headers = ">=4.3.0,<4.5"
django-crispy-forms = ">=2.1,<2.3"
django-filter = ">=23.4,<24.3"
django-redis = ">=5.4.0,<6.0"
Django = { extras = ["argon2"], version = ">=5.0,<5.1" }
djangorestframework = ">=3.15.0,<3.16"
filelock = "<4,>=3.12.2"
"fluent.syntax" = ">=0.18.1,<0.20"
GitPython = ">=3.1.0,<3.2"
hiredis = ">=2.2.1,<2.4"
html2text = ">=2024.2.25,<2024.2.27"
iniparse = "==0.5"
jsonschema = ">=4.5,<5"
lxml = ">=5.2.0,<5.3"
misaka = ">=2.1.0,<2.2"
mistletoe = ">=1.3.0,<1.4"
nh3 = ">=0.2.14,<0.3"
openpyxl = ">=3.1.0,<3.2"
packaging = ">=22,<24.2"
phply = ">=1.2.6,<1.3"
Pillow = ">=10.3.0,<10.4"
pycairo = ">=1.20.0"
Pygments = ">=2.15.0,<3.0"
PyGObject = ">=3.40.1"
pyicumessageformat = ">=1.0.0,<1.1"
pyparsing = ">=3.1.1,<3.2"
python-dateutil = ">=2.8.2"
python-redis-lock = { extras = ["django"], version = ">=4,<4.1" }
rapidfuzz = ">=2.6.0,<3.10"
redis = ">=5.0.2,<5.1.0"
requests = ">=2.32.2,<2.33"
"ruamel.yaml" = ">=0.17.2,<0.19.0"
sentry-sdk = ">=2.2,<3.0"
siphashc = ">=2.1,<3.0"
social-auth-app-django = ">=5.4.0,<6.0.0"
social-auth-core = ">=4.5.0,<5.0.0"
tesserocr = ">=2.6.1,<2.8.0"
translate-toolkit = ">=3.13.1,<3.14"
translation-finder = ">=2.16,<3.0"
user-agents = ">=2.0,<2.3"
weblate-language-data = ">=2024.3"
weblate-schemas = "==2024.1"
psycopg = ">=3.1.8,<4"
psycopg-binary = ">=3.1.8,<4"


[tool.poetry.dev-dependencies]

