# This file has been autogenerated.
# Update by running the updateScript.
# Note that some sections may not be supported by the updateScript yet, so
# please check the diff of the resulting file.
{
  boards = [
    "librem_11"
    "librem_13v2"
    "librem_13v4"
    "librem_14"
    "librem_15v3"
    "librem_15v4"
    "librem_l1um"
    "librem_l1um_v2"
    "librem_mini"
    "librem_mini_v2"
    "novacustom-nv4x_adl"
    "novacustom-v540tu"
    "novacustom-v560tu"
    "optiplex-7010_9010-hotp-maximized"
    "optiplex-7010_9010-maximized"
    "optiplex-7010_9010_TXT-hotp-maximized"
    "optiplex-7010_9010_TXT-maximized"
    "qemu-coreboot-fbwhiptail-tpm1"
    "qemu-coreboot-fbwhiptail-tpm1-hotp"
    "qemu-coreboot-fbwhiptail-tpm1-hotp-prod"
    "qemu-coreboot-fbwhiptail-tpm1-hotp-prod_quiet"
    "qemu-coreboot-fbwhiptail-tpm1-prod"
    "qemu-coreboot-fbwhiptail-tpm2"
    "qemu-coreboot-fbwhiptail-tpm2-hotp"
    "qemu-coreboot-fbwhiptail-tpm2-hotp-prod"
    "qemu-coreboot-fbwhiptail-tpm2-hotp-prod_quiet"
    "qemu-coreboot-fbwhiptail-tpm2-prod"
    "qemu-coreboot-whiptail-tpm1"
    "qemu-coreboot-whiptail-tpm1-hotp"
    "qemu-coreboot-whiptail-tpm1-hotp-prod"
    "qemu-coreboot-whiptail-tpm1-prod"
    "qemu-coreboot-whiptail-tpm2"
    "qemu-coreboot-whiptail-tpm2-hotp"
    "qemu-coreboot-whiptail-tpm2-hotp-prod"
    "qemu-coreboot-whiptail-tpm2-prod"
    "t420-hotp-maximized"
    "t420-maximized"
    "t430-hotp-maximized"
    "t430-maximized"
    "t480-hotp-maximized"
    "t480-maximized"
    "UNMAINTAINED_kgpe-d16_server"
    "UNMAINTAINED_kgpe-d16_server-whiptail"
    "UNMAINTAINED_kgpe-d16_workstation"
    "UNMAINTAINED_kgpe-d16_workstation-usb_keyboard"
    "UNTESTED_nitropad-ns50"
    "UNTESTED_t440p-hotp-maximized"
    "UNTESTED_t440p-maximized"
    "UNTESTED_t530-hotp-maximized"
    "UNTESTED_t530-maximized"
    "UNTESTED_talos-2"
    "UNTESTED_w541-hotp-maximized"
    "UNTESTED_w541-maximized"
    "UNTESTED_z220-cmt-hotp-maximized"
    "UNTESTED_z220-cmt-maximized"
    "w530-hotp-maximized"
    "w530-maximized"
    "x220-hotp-maximized"
    "x220-maximized"
    "x230-hotp-maximized"
    "x230-hotp-maximized-fhd_edp"
    "x230-hotp-maximized_usb-kb"
    "x230-maximized"
    "x230-maximized-fhd_edp"
  ];
  modules = [
    {
      name = "coreboot-24.12";
      url = "https://github.com/coreboot/coreboot";
      pinned = true;
      rev = "2f1e4e5e8515dd350cc9d68b48d32a5b6b02ae6a";
      hash = "sha256-NA0yN4igJR7QTmdLzvvI2p21ObslqU8iFHynEWpLM5I=";
    }
    {
      name = "coreboot-dasharo";
      url = "https://github.com/dasharo/coreboot";
      pinned = true;
      rev = "94e5f5d5b808cf8d8fd5c70d4ef6a08a054f8986";
      hash = "sha256-n0wlP7thamybBDAwY1/SAWvwsW7NIJOiaAs406GCuV8=";
    }
    {
      name = "coreboot-purism";
      url = "https://source.puri.sm/firmware/coreboot.git";
      pinned = true;
      rev = "bea9947a1279be7d4a72b38a601d0288d10d1cb8";
      hash = "sha256-AyyAC8OM1B8qE6Bs47SyCEFyVeyIGrVEWDqf2xb3cDo=";
    }
    {
      name = "coreboot-talos_2";
      url = "https://github.com/Dasharo/coreboot";
      pinned = true;
      rev = "fc47236e9877f4113dfcce07fa928f52d4d2c8ee";
      hash = "sha256-wvb2ln2XfE8plTp7mYBCcv3EhX2QSAzPf0h7mTh+wis=";
    }
    {
      name = "linuxboot";
      url = "https://github.com/osresearch/linuxboot";
      pinned = false;
      rev = "b5376a441e8e85cbf722e943bb8294958e87c784";
      hash = "sha256-W51FE4mYpodu+IvcV56668Ory2WGFVwudAnG3VIlsq0=";
    }
  ];
  pkgs = [
    {
      name = "bash-5.1.16.tar.gz";
      url = "https://ftp.gnu.org/gnu/bash/bash-5.1.16.tar.gz";
      hash = "sha256-W6wXIY05EYNFINrRPNH4WrlE4cCa4aulWQa+H4GS9Vg=";
    }
    {
      name = "busybox-1.36.1.tar.bz2";
      url = "https://busybox.net/downloads/busybox-1.36.1.tar.bz2";
      hash = "sha256-uMwkyVdNgJ5yecO+NJeVxdXOtv3xnKcJ+AzeUOR94xQ=";
    }
    {
      name = "cairo-1.14.12.tar.xz";
      url = "https://www.cairographics.org/releases/cairo-1.14.12.tar.xz";
      hash = "sha256-jJDwDFALIpnAoyPdm+6tKgA1N1KyCS6tVYE5vWf3vxY=";
    }
    {
      name = "coreboot-24.02.01.tar.xz";
      url = "https://www.coreboot.org/releases/coreboot-24.02.01.tar.xz";
      hash = "sha256-5W9cDJAIv97BxL5kCawJNoAUD5RB79PV5Hve/8v3flA=";
    }
    {
      name = "coreboot-4.20.1.tar.xz";
      url = "https://www.coreboot.org/releases/coreboot-4.20.1.tar.xz";
      hash = "sha256-tBU5qMLqsv7HUhV+tKy9DipjenIDUwwS5mtDpcPDqTE=";
    }
    {
      name = "coreboot-4.22.01.tar.xz";
      url = "https://www.coreboot.org/releases/coreboot-4.22.01.tar.xz";
      hash = "sha256-PRo237KmVBM8fzbPTaQ28NefU1ZEBprf583K2WJTLD8=";
    }
    {
      name = "coreboot-blobs-24.02.01.tar.xz";
      url = "https://www.coreboot.org/releases/coreboot-blobs-24.02.01.tar.xz";
      hash = "sha256-jQO4LNKyWTRz1M1RHHvvf91Dg5I39sN6g4MWFmDBRCc=";
    }
    {
      name = "coreboot-blobs-4.20.1.tar.xz";
      url = "https://www.coreboot.org/releases/coreboot-blobs-4.20.1.tar.xz";
      hash = "sha256-MPnYYY541IPQkDl2mCSF5wglyjRp79F5Askkaq79fEo=";
    }
    {
      name = "coreboot-blobs-4.22.01.tar.xz";
      url = "https://www.coreboot.org/releases/coreboot-blobs-4.22.01.tar.xz";
      hash = "sha256-S7mPGhzIs8cASh1yBGK//w/jSpEGFj3ycIuVK938UgM=";
    }
    {
      name = "cryptsetup-2.6.1.tar.xz";
      url = "https://www.kernel.org/pub/linux/utils/cryptsetup/v2.6/cryptsetup-2.6.1.tar.xz";
      hash = "sha256-QQ3tZaEHKrnI5Brd7Te5cpwIf+9NLbArtO9SmtbaRpM=";
    }
    {
      name = "cryptsetup-1.7.3.tar.xz";
      url = "https://www.kernel.org/pub/linux/utils/cryptsetup/v1.7/cryptsetup-1.7.3.tar.xz";
      hash = "sha256-rysE6Edc9AuNn/2Xoaz6c6p4fIkEMK/YmAT7VE1q3AI=";
    }
    {
      name = "dropbear-2016.74.tar.bz2";
      url = "https://mirror.dropbear.nl/mirror/releases/dropbear-2016.74.tar.bz2";
      hash = "sha256-JyDqVO0AmvgScBvMKQoqYB1cEH0SmT5dksD1+B9xiJE=";
    }
    {
      name = "e2fsprogs-1.47.0.tar.xz";
      url = "https://mirrors.edge.kernel.org/pub/linux/kernel/people/tytso/e2fsprogs/v1.47.0/e2fsprogs-1.47.0.tar.xz";
      hash = "sha256-FEr1Pyu9khzvb4vqiLufrdyoZdo/vGV8ybTSABCX1ds=";
    }
    {
      name = "exfatprogs-1.2.1.tar.xz";
      url = "https://github.com/exfatprogs/exfatprogs/releases/download/1.2.1/exfatprogs-1.2.1.tar.xz";
      hash = "sha256-pvOx+0vTeDXI+MtCGqxOt1uIClE0KymFDEBjlzFiIns=";
    }
    {
      name = "fbwhiptail-1.3.tar.gz";
      url = "https://source.puri.sm/firmware/fbwhiptail/-/archive/1.3/fbwhiptail-1.3.tar.gz";
      hash = "sha256-Lrj639Pi1XTeUjJ7vIDtYxNzmj259Nh4QMU0NSxm31o=";
    }
    {
      name = "flashprog-eb2c04185f8f471c768b742d66e4c552effdd9cb.tar.gz";
      url = "https://github.com/SourceArcade/flashprog/archive/eb2c04185f8f471c768b742d66e4c552effdd9cb.tar.gz";
      hash = "sha256-DUGGvp8giNYkqacIw1LQ36+iJk4UNrEew8waNQ/UWnc=";
    }
    {
      name = "flashrom-1776bb46ba6ea3d1ab2ec3f0cd88158aabed7400.tar.gz";
      url = "https://github.com/flashrom/flashrom/archive/1776bb46ba6ea3d1ab2ec3f0cd88158aabed7400.tar.gz";
      hash = "sha256-ZeJiykQooM7d1z9IHtDYREOTtzp4Rp8makRX38g07Lc=";
    }
    {
      name = "flashtools-d1e6f12568cb23387144a4b7a6535fe1bc1e79b1.tar.gz";
      url = "https://github.com/osresearch/flashtools/archive/d1e6f12568cb23387144a4b7a6535fe1bc1e79b1.tar.gz";
      hash = "sha256-pozbSi4xL5aGIRmm2CmskAtT0MvIDKpWMu/UO1t+7Ww=";
    }
    {
      name = "frotz-2.44.tar.gz";
      url = "https://github.com/DavidGriffith/frotz/archive/2.44.tar.gz";
      hash = "sha256-27XrO8lSddy5hMS9uupYvB8bCFsgCSzm6G2fC/O6hY8=";
    }
    {
      name = "gnupg-2.4.0.tar.bz2";
      url = "https://www.gnupg.org/ftp/gcrypt/gnupg/gnupg-2.4.0.tar.bz2";
      hash = "sha256-HXkVjdAdmSQx3S4/rLif2slxJ/iXhOosthDGAPsMFIM=";
    }
    {
      name = "gnupg-1.4.21.tar.bz2";
      url = "https://www.gnupg.org/ftp/gcrypt/gnupg/gnupg-1.4.21.tar.bz2";
      hash = "sha256-a0ejEAyFfcqzxg5hUuVqmX8seGLBuLKyWt84hKGuInY=";
    }
    {
      name = "hidapi-e5ae0d30a523c565595bdfba3d5f2e9e1faf0bd0.tar.xz";
      url = "https://github.com/Nitrokey/hidapi/archive/e5ae0d30a523c565595bdfba3d5f2e9e1faf0bd0.tar.gz";
      hash = "sha256-rMKlCJqJFwhcKz6+lEYGWiHHYLp+E8tUkXBDxBIhiOA=";
    }
    {
      name = "nitrokey-hotp-verification-f4583b701a354dfa50c690075a568bc5cdf160e1.tar.gz";
      url = "https://github.com/Nitrokey/nitrokey-hotp-verification/archive/f4583b701a354dfa50c690075a568bc5cdf160e1.tar.gz";
      hash = "sha256-Qu/rqaYeSgDfVb9TN8FXlIvHbIlUEPx20CuH1s07OOs=";
    }
    {
      name = "io386-fc73fcf8e51a70638679c3e9b0ada10527f8a7c1.tar.gz";
      url = "https://github.com/hardenedlinux/io386/archive/fc73fcf8e51a70638679c3e9b0ada10527f8a7c1.tar.gz";
      hash = "sha256-h0iYr1fYbcBXzqObSn4GIfxkqk+3d9+x7rEekTS8mgY=";
    }
    {
      name = "ioport_1.2.orig.tar.gz";
      url = "https://deb.debian.org/debian/pool/main/i/ioport/ioport_1.2.orig.tar.gz";
      hash = "sha256-f6wcS2HrlBEnXeDh59eow/NBZvZPFkE/UHQej84rjcA=";
    }
    {
      name = "json-c-0.14.tar.gz";
      url = "https://s3.amazonaws.com/json-c_releases/releases/json-c-0.14-nodoc.tar.gz";
      hash = "sha256-mZFOZEolIB2CzO+iBDD3UVwRCSM2D570Z1VSfAJBKvo=";
    }
    {
      name = "kbd-2.6.1.tar.gz";
      url = "https://www.kernel.org/pub/linux/utils/kbd/kbd-2.6.1.tar.gz";
      hash = "sha256-qu1TChSQ1j0EFEg3LirU84wxeQQpAyUQALcdUnxG6UU=";
    }
    {
      name = "kexec-tools-2.0.26.tar.gz";
      url = "https://kernel.org/pub/linux/utils/kernel/kexec/kexec-tools-2.0.26.tar.gz";
      hash = "sha256-ib3ZQVQsZP7BYxGFjfME7To5CMGmCHTWnfXZvxYR4GI=";
    }
    {
      name = "libaio_0.3.113.orig.tar.gz";
      url = "https://deb.debian.org/debian/pool/main/liba/libaio/libaio_0.3.113.orig.tar.gz";
      hash = "sha256-LETRxf0NQ3Uih8muHrnAI/BO+EjqjUqvpG6a7bZ4IAs=";
    }
    {
      name = "libassuan-2.5.5.tar.bz2";
      url = "https://gnupg.org/ftp/gcrypt/libassuan/libassuan-2.5.5.tar.bz2";
      hash = "sha256-jowvzJgvnKZ9y7HZXi3HRrFzmkZovCCzo8W+Yy7bNOQ=";
    }
    {
      name = "libgcrypt-1.10.1.tar.bz2";
      url = "https://gnupg.org/ftp/gcrypt/libgcrypt/libgcrypt-1.10.1.tar.bz2";
      hash = "sha256-7xSuVGsAhM2EJZ9hpV4Ho4w7U6/A9Ua//O8vAbr/6d4=";
    }
    {
      name = "libgpg-error-1.46.tar.bz2";
      url = "https://gnupg.org/ftp/gcrypt/libgpg-error/libgpg-error-1.46.tar.bz2";
      hash = "sha256-t+EaZCRrvl7zd0jeQ7JFq9cs/NU8muXn/FylnxyBJo0=";
    }
    {
      name = "hidapi-0.9.0.tar.gz";
      url = "https://github.com/libusb/hidapi/archive/hidapi-0.9.0.tar.gz";
      hash = "sha256-Yw7hg0vdXFdhqwef0E9GOolYXfj8rlGnv+Qimx4CplI=";
    }
    {
      name = "libksba-1.6.3.tar.bz2";
      url = "https://gnupg.org/ftp/gcrypt/libksba/libksba-1.6.3.tar.bz2";
      hash = "sha256-P3LGjbMJceu/FDZ1J3GUI/Ck1fgQP8n0ocAan6RA3lw=";
    }
    {
      name = "libnitrokey-v3.6.tar.gz";
      url = "https://github.com/Nitrokey/libnitrokey/releases/download/v3.6/libnitrokey-v3.6.tar.gz";
      hash = "sha256-TzOCthk6/mnCABMhA4/OlJC8KIA+1ocVKjl8zYkUauY=";
    }
    {
      name = "libpng-1.6.34.tar.gz";
      url = "https://github.com/glennrp/libpng-releases/raw/master/libpng-1.6.34.tar.gz";
      hash = "sha256-V0YjpJAamWkICrSi35Q3AmyKhxUN/VwjXijJSyEpZKc=";
    }
    {
      name = "libusb-compat-0.1.5.tar.bz2";
      url = "https://downloads.sourceforge.net/project/libusb/libusb-compat-0.1/libusb-compat-0.1.5/libusb-compat-0.1.5.tar.bz2";
      hash = "sha256-QE70trMkvnmsG/s9g56shg+8kp5qyx74h5Om6jKLxVo=";
    }
    {
      name = "libusb-1.0.21.tar.bz2";
      url = "https://github.com/libusb/libusb/releases/download/v1.0.21/libusb-1.0.21.tar.bz2";
      hash = "sha256-fc6czpqBGUtwZe6RK81V7v/rq2lOpAP/uRtn22axgks=";
    }
    {
      name = "linux-6.1.8.tar.xz";
      url = "https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.1.8.tar.xz";
      hash = "sha256-tgu1Ori6NwonBFSxHpPUGvKRJvxyvW7eUXZz4uV7gW0=";
    }
    {
      name = "linux-6.6.16.tar.xz";
      url = "https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.6.16.tar.xz";
      hash = "sha256-sh1XlaO+rU8RKRZCMiL6qKD1GeQgHfND4+uI3J5KqjA=";
    }
    {
      name = "LVM2.2.03.23.tgz";
      url = "https://mirrors.kernel.org/sourceware/lvm2/LVM2.2.03.23.tgz";
      hash = "sha256-dOeUqene4bz4ogZfZbkZbET98yHiLWO5jtfejJqhel0=";
    }
    {
      name = "mbedtls-2.4.2.tar.gz";
      url = "https://github.com/ARMmbed/mbedtls/archive/mbedtls-2.4.2.tar.gz";
      hash = "sha256-t6+rag+G4pxgVYSLcNGDxOJTHLDslVtmwOTht+SVS/Q=";
    }
    {
      name = "msr-tools-572ef8a2b873eda15a322daa48861140a078b92c.tar.gz";
      url = "https://github.com/osresearch/msr-tools/archive/572ef8a2b873eda15a322daa48861140a078b92c.tar.gz";
      hash = "sha256-gFVHkNCkBCBf4hXJro0t4VnpgOwjgh1jbyAfElUOasA=";
    }
    {
      name = "musl-cross-make-fd6be58297ee21fcba89216ccd0d4aca1e3f1c5c.tar.gz";
      url = "https://github.com/richfelker/musl-cross-make/archive/fd6be58297ee21fcba89216ccd0d4aca1e3f1c5c.tar.gz";
      hash = "sha256-FbjgoofXOKRuBp6Q1nqNliE7NXt5qvPozwzUDksjDZ4=";
    }
    {
      name = "ncurses-6.5.tar.gz";
      url = "https://invisible-island.net/archives/ncurses/ncurses-6.5.tar.gz";
      hash = "sha256-E22RvCaamleF5fnpgLx2q1dCj2BM4+WlqQzrx2eXHMY=";
    }
    {
      name = "newt-0.52.24.tar.gz";
      url = "https://releases.pagure.org/newt/newt-0.52.24.tar.gz";
      hash = "sha256-Xe1+Ih+F9kJSHEmxgmyN4ZhFqjcrr11jClF3S1RPvbs=";
    }
    {
      name = "nkstorecli-0.4.1.tar.gz";
      url = "https://github.com/Nitrokey/nitrokey-storage-cli/releases/download/v0.4.1/nkstorecli-0.4.1.tar.gz";
      hash = "sha256-D6fbvt5FO5xA2SDAVjr90rD30IYlrraPBlUSYTtvu2s=";
    }
    {
      name = "npth-1.6.tar.bz2";
      url = "https://gnupg.org/ftp/gcrypt/npth/npth-1.6.tar.bz2";
      hash = "sha256-E5Or2a3PB2LTR5jcNP3PTQ0iqEEHIedvHjr80dqk4tE=";
    }
    {
      name = "openssl-3.0.8.tar.gz";
      url = "https://www.openssl.org/source/openssl-3.0.8.tar.gz";
      hash = "sha256-bBPSvzj98x6sPOKjRwc2c/XWMmM5jx9p0N9KQSU+Sz4=";
    }
    {
      name = "pciutils-3.5.4.tar.xz";
      url = "https://www.kernel.org/pub/software/utils/pciutils/pciutils-3.5.4.tar.xz";
      hash = "sha256-ZCk8arkxjEDvJit22HvZCXUxdZdSusVW5Ql5seY8/mY=";
    }
    {
      name = "pinentry-1.1.0.tar.bz2";
      url = "https://www.gnupg.org/ftp/gcrypt/pinentry/pinentry-1.1.0.tar.bz2";
      hash = "sha256-aAdmhvpySikOpJzfDRwMFQCQfRt1mjvL++wCk+j1ZXA=";
    }
    {
      name = "pixman-0.34.0.tar.gz";
      url = "https://www.cairographics.org/releases/pixman-0.34.0.tar.gz";
      hash = "sha256-IbaySbUcaADclVO2UQbh430OJd+ULJBTHUw5l6ogqI4=";
    }
    {
      name = "popt-1.19.tar.gz";
      url = "https://fossies.org/linux/misc/popt-1.19.tar.gz";
      hash = "sha256-wlpIOPyOTByKrLi9Yg7bMISj1jv4mH/a08onWMYyQPk=";
    }
    {
      name = "powerpc-utils-1.3.5.tar.gz";
      url = "https://github.com/ibm-power-utilities/powerpc-utils/archive/v1.3.5/powerpc-utils-1.3.5.tar.gz";
      hash = "sha256-d+/jl4rJwlHEcoo1ua69YHZYOTmo4mzH8H/6hkMqi/A=";
    }
    {
      name = "purism-blobs-995f66c445841b86e6596e9b297cc4888c0257e5.tar.gz";
      url = "https://source.puri.sm/firmware/purism-blobs/-/archive/995f66c445841b86e6596e9b297cc4888c0257e5/purism-blobs-995f66c445841b86e6596e9b297cc4888c0257e5.tar.gz";
      hash = "sha256-bSbBKf6NcZpJ9PcmODuq9+22ExGDutpBZ3EbWlMS9RY=";
    }
    {
      name = "qrencode-3.4.4.tar.gz";
      url = "https://web.archive.org/web/20240910005455/https://fukuchi.org/works/qrencode/qrencode-3.4.4.tar.gz";
      hash = "sha256-55TiapYBkBPA42ZcsGsYmSZo81LFVT0KVT9dFE9/KnI=";
    }
    {
      name = "slang-2.3.3.tar.bz2";
      url = "https://www.jedsoft.org/releases/slang/slang-2.3.3.tar.bz2";
      hash = "sha256-+RRQVK4TGXPGEgjqgkhtXdEOPFza0jt8SgYXdDyPWhg=";
    }
    {
      name = "tpm2-tools-5.6.tar.gz";
      url = "https://github.com/tpm2-software/tpm2-tools/releases/download/5.6/tpm2-tools-5.6.tar.gz";
      hash = "sha256-Usi8uq3KCCq/5et+5JZ9LWMthLFndnXy8HG20uwizsM=";
    }
    {
      name = "tpm2-tss-3.2.2.tar.gz";
      url = "https://github.com/tpm2-software/tpm2-tss/releases/download/3.2.2/tpm2-tss-3.2.2.tar.gz";
      hash = "sha256-up5SEX8lTzV/9QLn1g/OZSs7+yYyfSNrv1q2NCNeQPE=";
    }
    {
      name = "tpmtotp-4d63d21c8b7db2e92ddb393057f168aead147f47.tar.gz";
      url = "https://github.com/osresearch/tpmtotp/archive/4d63d21c8b7db2e92ddb393057f168aead147f47.tar.gz";
      hash = "sha256-6qwej2UvHaf1oe1qjP77ZRHx5eHav5O0TbOynBjFrlM=";
    }
    {
      name = "util-linux-2.39.tar.xz";
      url = "https://www.kernel.org/pub/linux/utils/util-linux/v2.39/util-linux-2.39.tar.xz";
      hash = "sha256-MrMKM2zakDGC7WH+s+m5CLdipeZv4U5D77iNNxYgdcs=";
    }
    {
      name = "zlib-1.2.11.tar.gz";
      url = "https://zlib.net/fossils/zlib-1.2.11.tar.gz";
      hash = "sha256-w+Xp/dUATctUL+2l7k8P8HRGKLr47S3V1m+MoRl8saE=";
    }
    {
      name = "zstd-1.5.5.tar.gz";
      url = "https://github.com/facebook/zstd/releases/download/v1.5.5/zstd-1.5.5.tar.gz";
      hash = "sha256-nEOWzIKc+uMZpuJhUgLoKq1BNyBzSC/OKG+seGRtPuQ=";
    }
  ];
  crossgcc-deps = {
    "coreboot-24.12" = [
      {
        name = "coreboot-crossgcc-gmp-6.3.0.tar.xz";
        url = "https://ftp.gnu.org/gnu/gmp/gmp-6.3.0.tar.xz";
        hash = "sha256-o8K4AgG4nmhhb0rTC8Zq7kknw85Q4zkpyoGdXENTiJg=";
      }
      {
        name = "coreboot-crossgcc-mpfr-4.2.1.tar.xz";
        url = "https://ftp.gnu.org/gnu/mpfr/mpfr-4.2.1.tar.xz";
        hash = "sha256-J3gHNTpnJpeJlpRa8T5Sgp46vXqaW3+yeTiU4Y8fy7I=";
      }
      {
        name = "coreboot-crossgcc-mpc-1.3.1.tar.gz";
        url = "https://ftp.gnu.org/gnu/mpc/mpc-1.3.1.tar.gz";
        hash = "sha256-q2QkkvXPiCt0qgy3MM1BCoHtzb7IlRg86TDnBsHHWbg=";
      }
      {
        name = "coreboot-crossgcc-gcc-14.2.0.tar.xz";
        url = "https://ftp.gnu.org/gnu/gcc/gcc-14.2.0/gcc-14.2.0.tar.xz";
        hash = "sha256-p7Obxpy/niWCbFpgqyZHcAH3wI2FzsBLwOKcq+1vPMk=";
      }
      {
        name = "coreboot-crossgcc-binutils-2.43.1.tar.xz";
        url = "https://ftp.gnu.org/gnu/binutils/binutils-2.43.1.tar.xz";
        hash = "sha256-E/dCAqPExREYt5ejnqQgDT9s++Ik2m0dlbuThIATLf0=";
      }
      {
        name = "coreboot-crossgcc-acpica-unix-20241212.tar.gz";
        url = "https://github.com/acpica/acpica/releases/download/R2024_12_12/acpica-unix-20241212.tar.gz";
        hash = "sha256-ncqDz+45C3EEhfvfeHBINwBJwFcjsQzCIM/vbhPDGWE=";
      }
      {
        name = "coreboot-crossgcc-lld-18.1.8.src.tar.xz";
        url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.8/lld-18.1.8.src.tar.xz";
        hash = "sha256-gA5oBfthPrhCj3oZn20GxMGfePLbaRV6EpuwT8HJl2k=";
      }
      {
        name = "coreboot-crossgcc-llvm-18.1.8.src.tar.xz";
        url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.8/llvm-18.1.8.src.tar.xz";
        hash = "sha256-9oz5Dzabx9AVi6cNhgsMs028Fj1v8OvGz6XlFbmy4o0=";
      }
      {
        name = "coreboot-crossgcc-clang-18.1.8.src.tar.xz";
        url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.8/clang-18.1.8.src.tar.xz";
        hash = "sha256-VyT+ChMIfVV5EEzt0vizvBCiEvt5oPzayY9IgOGfRRk=";
      }
      {
        name = "coreboot-crossgcc-cmake-18.1.8.src.tar.xz";
        url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.8/cmake-18.1.8.src.tar.xz";
        hash = "sha256-Wbre9ZLdNIk80xnUKzI6qpkLRS0FxxgP8g8jqxtB6Dc=";
      }
      {
        name = "coreboot-crossgcc-compiler-rt-18.1.8.src.tar.xz";
        url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.8/compiler-rt-18.1.8.src.tar.xz";
        hash = "sha256-4FTpmpySQHIGFukny1I2OrvItPHvAoa609957I/fiS8=";
      }
      {
        name = "coreboot-crossgcc-clang-tools-extra-18.1.8.src.tar.xz";
        url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.8/clang-tools-extra-18.1.8.src.tar.xz";
        hash = "sha256-5Yh3/Nle0QaCS9GjEnbdF+0MU63NYMp1KJ6sBlTwp/E=";
      }
      {
        name = "coreboot-crossgcc-libunwind-18.1.8.src.tar.xz";
        url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.8/libunwind-18.1.8.src.tar.xz";
        hash = "sha256-wxV30Wl4sNoORy73UfdIk6W0WafqSjg7dferk88eaHc=";
      }
      {
        name = "coreboot-crossgcc-cmake-3.31.3.tar.gz";
        url = "https://cmake.org/files/v3.31/cmake-3.31.3.tar.gz";
        hash = "sha256-+sRbxtQQtJsxE6uGYHSIjWyencgaFBh0RG6yOaw4y4c=";
      }
      {
        name = "coreboot-crossgcc-nasm-2.16.03.tar.bz2";
        url = "https://www.nasm.us/pub/nasm/releasebuilds/2.16.03/nasm-2.16.03.tar.bz2";
        hash = "sha256-vvPeFZvNYa35i7fMh+6QRulEZErXa3Yz8YqwY+2ynlc=";
      }
      {
        name = "coreboot-crossgcc-gcc-14.2.0.tar.xz";
        url = "https://ftp.gnu.org/gnu/gcc/gcc-14.2.0/gcc-14.2.0.tar.xz";
        hash = "sha256-p7Obxpy/niWCbFpgqyZHcAH3wI2FzsBLwOKcq+1vPMk=";
      }
    ];
    "coreboot-dasharo" = [
      {
        name = "coreboot-crossgcc-gmp-6.3.0.tar.xz";
        url = "https://ftp.gnu.org/gnu/gmp/gmp-6.3.0.tar.xz";
        hash = "sha256-o8K4AgG4nmhhb0rTC8Zq7kknw85Q4zkpyoGdXENTiJg=";
      }
      {
        name = "coreboot-crossgcc-mpfr-4.2.1.tar.xz";
        url = "https://ftp.gnu.org/gnu/mpfr/mpfr-4.2.1.tar.xz";
        hash = "sha256-J3gHNTpnJpeJlpRa8T5Sgp46vXqaW3+yeTiU4Y8fy7I=";
      }
      {
        name = "coreboot-crossgcc-mpc-1.3.1.tar.gz";
        url = "https://ftp.gnu.org/gnu/mpc/mpc-1.3.1.tar.gz";
        hash = "sha256-q2QkkvXPiCt0qgy3MM1BCoHtzb7IlRg86TDnBsHHWbg=";
      }
      {
        name = "coreboot-crossgcc-gcc-13.2.0.tar.xz";
        url = "https://ftp.gnu.org/gnu/gcc/gcc-13.2.0/gcc-13.2.0.tar.xz";
        hash = "sha256-4nXnZEKmBnNBon8Exca4PYYTFEAEwEE1KIY9xrXHQ9o=";
      }
      {
        name = "coreboot-crossgcc-binutils-2.41.tar.xz";
        url = "https://ftp.gnu.org/gnu/binutils/binutils-2.41.tar.xz";
        hash = "sha256-rppXieI0WeWWBuZxRyPy0//DHAMXQZHvDQFb3wYAdFA=";
      }
      {
        name = "coreboot-crossgcc-R06_28_23.tar.gz";
        url = "https://github.com/acpica/acpica/archive/refs/tags/R06_28_23.tar.gz";
        hash = "sha256-Ikh5m3ygincRrIfTGSQ1TtSQR1B2B9AzvTJ7qGHsTTE=";
      }
      {
        name = "coreboot-crossgcc-llvm-16.0.6.src.tar.xz";
        url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.6/llvm-16.0.6.src.tar.xz";
        hash = "sha256-6R20TRs7scM/zqmn0fJCO4g+qpFj09VsoqptLwcRvCk=";
      }
      {
        name = "coreboot-crossgcc-clang-16.0.6.src.tar.xz";
        url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.6/clang-16.0.6.src.tar.xz";
        hash = "sha256-EYa25u7+rdCZEu1zs3KehbWfBDckuygYqVouwCRXGEA=";
      }
      {
        name = "coreboot-crossgcc-cmake-16.0.6.src.tar.xz";
        url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.6/cmake-16.0.6.src.tar.xz";
        hash = "sha256-OdNCpBYQldLyj7ElPkWFl4rFBSERfaZm4rH28oti9RQ=";
      }
      {
        name = "coreboot-crossgcc-compiler-rt-16.0.6.src.tar.xz";
        url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.6/compiler-rt-16.0.6.src.tar.xz";
        hash = "sha256-eRGiqcyhA5Ohf2N8Aab1VVsKOPZP9H3JFoQTpBkLwts=";
      }
      {
        name = "coreboot-crossgcc-clang-tools-extra-16.0.6.src.tar.xz";
        url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.6/clang-tools-extra-16.0.6.src.tar.xz";
        hash = "sha256-F0x4RNslkLGLKlmpzlA/j+Q57cLeLw9iUAZQHJlzbzE=";
      }
      {
        name = "coreboot-crossgcc-cmake-3.27.7.tar.gz";
        url = "https://cmake.org/files/v3.27/cmake-3.27.7.tar.gz";
        hash = "sha256-CPcaEGA2vwUfaSdg75VYwFd8Qqw56Wugl+dmK9QVjY4=";
      }
      {
        name = "coreboot-crossgcc-nasm-2.16.01.tar.bz2";
        url = "https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/nasm-2.16.01.tar.bz2";
        hash = "sha256-NbatLuBI1BxHefBz8+/Kd2KoIrfS1O9OjfJM9ldHuy4=";
      }
    ];
    "coreboot-purism" = [
      {
        name = "coreboot-crossgcc-gmp-6.3.0.tar.xz";
        url = "https://ftp.gnu.org/gnu/gmp/gmp-6.3.0.tar.xz";
        hash = "sha256-o8K4AgG4nmhhb0rTC8Zq7kknw85Q4zkpyoGdXENTiJg=";
      }
      {
        name = "coreboot-crossgcc-mpfr-4.2.1.tar.xz";
        url = "https://ftp.gnu.org/gnu/mpfr/mpfr-4.2.1.tar.xz";
        hash = "sha256-J3gHNTpnJpeJlpRa8T5Sgp46vXqaW3+yeTiU4Y8fy7I=";
      }
      {
        name = "coreboot-crossgcc-mpc-1.3.1.tar.gz";
        url = "https://ftp.gnu.org/gnu/mpc/mpc-1.3.1.tar.gz";
        hash = "sha256-q2QkkvXPiCt0qgy3MM1BCoHtzb7IlRg86TDnBsHHWbg=";
      }
      {
        name = "coreboot-crossgcc-gcc-13.2.0.tar.xz";
        url = "https://ftp.gnu.org/gnu/gcc/gcc-13.2.0/gcc-13.2.0.tar.xz";
        hash = "sha256-4nXnZEKmBnNBon8Exca4PYYTFEAEwEE1KIY9xrXHQ9o=";
      }
      {
        name = "coreboot-crossgcc-binutils-2.41.tar.xz";
        url = "https://ftp.gnu.org/gnu/binutils/binutils-2.41.tar.xz";
        hash = "sha256-rppXieI0WeWWBuZxRyPy0//DHAMXQZHvDQFb3wYAdFA=";
      }
      {
        name = "coreboot-crossgcc-R06_28_23.tar.gz";
        url = "https://github.com/acpica/acpica/archive/refs/tags/R06_28_23.tar.gz";
        hash = "sha256-Ikh5m3ygincRrIfTGSQ1TtSQR1B2B9AzvTJ7qGHsTTE=";
      }
      {
        name = "coreboot-crossgcc-llvm-16.0.6.src.tar.xz";
        url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.6/llvm-16.0.6.src.tar.xz";
        hash = "sha256-6R20TRs7scM/zqmn0fJCO4g+qpFj09VsoqptLwcRvCk=";
      }
      {
        name = "coreboot-crossgcc-clang-16.0.6.src.tar.xz";
        url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.6/clang-16.0.6.src.tar.xz";
        hash = "sha256-EYa25u7+rdCZEu1zs3KehbWfBDckuygYqVouwCRXGEA=";
      }
      {
        name = "coreboot-crossgcc-cmake-16.0.6.src.tar.xz";
        url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.6/cmake-16.0.6.src.tar.xz";
        hash = "sha256-OdNCpBYQldLyj7ElPkWFl4rFBSERfaZm4rH28oti9RQ=";
      }
      {
        name = "coreboot-crossgcc-compiler-rt-16.0.6.src.tar.xz";
        url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.6/compiler-rt-16.0.6.src.tar.xz";
        hash = "sha256-eRGiqcyhA5Ohf2N8Aab1VVsKOPZP9H3JFoQTpBkLwts=";
      }
      {
        name = "coreboot-crossgcc-clang-tools-extra-16.0.6.src.tar.xz";
        url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.6/clang-tools-extra-16.0.6.src.tar.xz";
        hash = "sha256-F0x4RNslkLGLKlmpzlA/j+Q57cLeLw9iUAZQHJlzbzE=";
      }
      {
        name = "coreboot-crossgcc-cmake-3.27.7.tar.gz";
        url = "https://cmake.org/files/v3.27/cmake-3.27.7.tar.gz";
        hash = "sha256-CPcaEGA2vwUfaSdg75VYwFd8Qqw56Wugl+dmK9QVjY4=";
      }
      {
        name = "coreboot-crossgcc-nasm-2.16.01.tar.bz2";
        url = "https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/nasm-2.16.01.tar.bz2";
        hash = "sha256-NbatLuBI1BxHefBz8+/Kd2KoIrfS1O9OjfJM9ldHuy4=";
      }
    ];
    "coreboot-talos_2" = [
      {
        name = "coreboot-crossgcc-gmp-6.2.1.tar.xz";
        url = "https://ftp.gnu.org/gnu/gmp/gmp-6.2.1.tar.xz";
        hash = "sha256-/UgpkSzd0S+EGBw0Ucx1K+IkZD6H+sSXtp7d2txJtPI=";
      }
      {
        name = "coreboot-crossgcc-mpfr-4.1.0.tar.xz";
        url = "https://ftp.gnu.org/gnu/mpfr/mpfr-4.1.0.tar.xz";
        hash = "sha256-DJij8XMv9spOppBVIHnanFl4ctMOluwoQU7iPJVVin8=";
      }
      {
        name = "coreboot-crossgcc-mpc-1.2.1.tar.gz";
        url = "https://ftp.gnu.org/gnu/mpc/mpc-1.2.1.tar.gz";
        hash = "sha256-F1A9LDld/PEGtiLcFCaDwRmUMdCVNnxqrLpu7DA0BFk=";
      }
      {
        name = "coreboot-crossgcc-gcc-11.2.0.tar.xz";
        url = "https://ftp.gnu.org/gnu/gcc/gcc-11.2.0/gcc-11.2.0.tar.xz";
        hash = "sha256-0I7cU2tUw3KhAQ/2YZ3SdMDxYDqkkhK6IPeqLNo2+os=";
      }
      {
        name = "coreboot-crossgcc-binutils-2.37.tar.xz";
        url = "https://ftp.gnu.org/gnu/binutils/binutils-2.37.tar.xz";
        hash = "sha256-gg2XJPAgo+acszeJOgtjwtsWHa3LDgb8Edwp6x6Eoyw=";
      }

      # Skipping acpica-unix2-20220331.tar.gz because we don't have a known-good mirror
      # Candidate (Heads explicitly *doesn't* use this one for this version): https://mirror.math.princeton.edu/pub/libreboot/misc/acpica/acpica-unix2-20220331.tar.gz
      # Candidate (involves an archive rename): https://distfiles.macports.org/acpica/acpica-unix-20220331.tar.gz

      {
        name = "coreboot-crossgcc-llvm-14.0.6.src.tar.xz";
        url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-14.0.6/llvm-14.0.6.src.tar.xz";
        hash = "sha256-BQki7KrKV4H99mMeqSvHFRg/IC+dLxUUcibwI0FPYZo=";
      }
      {
        name = "coreboot-crossgcc-clang-14.0.6.src.tar.xz";
        url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-14.0.6/clang-14.0.6.src.tar.xz";
        hash = "sha256-K1hHtqYxGLnv5chVSDY8gf/glrZsOzZ16VPiY0KuQDE=";
      }
      {
        name = "coreboot-crossgcc-compiler-rt-14.0.6.src.tar.xz";
        url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-14.0.6/compiler-rt-14.0.6.src.tar.xz";
        hash = "sha256-iN8wOEDKj7/5ROFeYcFBIm/nn10rjon7AkJk13hBoC4=";
      }
      {
        name = "coreboot-crossgcc-clang-tools-extra-14.0.6.src.tar.xz";
        url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-14.0.6/clang-tools-extra-14.0.6.src.tar.xz";
        hash = "sha256-fPO4/1bGXE0erjxWiD/EpsvD/586FTCnTWbkXScnGGY=";
      }
      {
        name = "coreboot-crossgcc-cmake-3.23.2.tar.gz";
        url = "https://cmake.org/files/v3.23/cmake-3.23.2.tar.gz";
        hash = "sha256-8xa0AFNGb5pBat+YHv2kGxYMqFnpf2pIS0R+opn/Jqo=";
      }
      {
        name = "coreboot-crossgcc-nasm-2.15.05.tar.bz2";
        url = "https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/nasm-2.15.05.tar.bz2";
        hash = "sha256-PEuDOeWrVLG8sjFhAfiYWl2lCj+eUE1D+m81ZovuL9A=";
      }
    ];
    "coreboot-24.02.01" = [
      {
        name = "coreboot-crossgcc-gmp-6.3.0.tar.xz";
        url = "https://ftp.gnu.org/gnu/gmp/gmp-6.3.0.tar.xz";
        hash = "sha256-o8K4AgG4nmhhb0rTC8Zq7kknw85Q4zkpyoGdXENTiJg=";
      }
      {
        name = "coreboot-crossgcc-mpfr-4.2.1.tar.xz";
        url = "https://ftp.gnu.org/gnu/mpfr/mpfr-4.2.1.tar.xz";
        hash = "sha256-J3gHNTpnJpeJlpRa8T5Sgp46vXqaW3+yeTiU4Y8fy7I=";
      }
      {
        name = "coreboot-crossgcc-mpc-1.3.1.tar.gz";
        url = "https://ftp.gnu.org/gnu/mpc/mpc-1.3.1.tar.gz";
        hash = "sha256-q2QkkvXPiCt0qgy3MM1BCoHtzb7IlRg86TDnBsHHWbg=";
      }
      {
        name = "coreboot-crossgcc-gcc-13.2.0.tar.xz";
        url = "https://ftp.gnu.org/gnu/gcc/gcc-13.2.0/gcc-13.2.0.tar.xz";
        hash = "sha256-4nXnZEKmBnNBon8Exca4PYYTFEAEwEE1KIY9xrXHQ9o=";
      }
      {
        name = "coreboot-crossgcc-binutils-2.41.tar.xz";
        url = "https://ftp.gnu.org/gnu/binutils/binutils-2.41.tar.xz";
        hash = "sha256-rppXieI0WeWWBuZxRyPy0//DHAMXQZHvDQFb3wYAdFA=";
      }
      {
        name = "coreboot-crossgcc-R06_28_23.tar.gz";
        url = "https://github.com/acpica/acpica/archive/refs/tags/R06_28_23.tar.gz";
        hash = "sha256-Ikh5m3ygincRrIfTGSQ1TtSQR1B2B9AzvTJ7qGHsTTE=";
      }
      {
        name = "coreboot-crossgcc-llvm-16.0.6.src.tar.xz";
        url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.6/llvm-16.0.6.src.tar.xz";
        hash = "sha256-6R20TRs7scM/zqmn0fJCO4g+qpFj09VsoqptLwcRvCk=";
      }
      {
        name = "coreboot-crossgcc-clang-16.0.6.src.tar.xz";
        url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.6/clang-16.0.6.src.tar.xz";
        hash = "sha256-EYa25u7+rdCZEu1zs3KehbWfBDckuygYqVouwCRXGEA=";
      }
      {
        name = "coreboot-crossgcc-cmake-16.0.6.src.tar.xz";
        url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.6/cmake-16.0.6.src.tar.xz";
        hash = "sha256-OdNCpBYQldLyj7ElPkWFl4rFBSERfaZm4rH28oti9RQ=";
      }
      {
        name = "coreboot-crossgcc-compiler-rt-16.0.6.src.tar.xz";
        url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.6/compiler-rt-16.0.6.src.tar.xz";
        hash = "sha256-eRGiqcyhA5Ohf2N8Aab1VVsKOPZP9H3JFoQTpBkLwts=";
      }
      {
        name = "coreboot-crossgcc-clang-tools-extra-16.0.6.src.tar.xz";
        url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.6/clang-tools-extra-16.0.6.src.tar.xz";
        hash = "sha256-F0x4RNslkLGLKlmpzlA/j+Q57cLeLw9iUAZQHJlzbzE=";
      }
      {
        name = "coreboot-crossgcc-cmake-3.27.7.tar.gz";
        url = "https://cmake.org/files/v3.27/cmake-3.27.7.tar.gz";
        hash = "sha256-CPcaEGA2vwUfaSdg75VYwFd8Qqw56Wugl+dmK9QVjY4=";
      }
      {
        name = "coreboot-crossgcc-nasm-2.16.01.tar.bz2";
        url = "https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/nasm-2.16.01.tar.bz2";
        hash = "sha256-NbatLuBI1BxHefBz8+/Kd2KoIrfS1O9OjfJM9ldHuy4=";
      }
    ];
    "coreboot-4.20.1" = [
      {
        name = "coreboot-crossgcc-gmp-6.2.1.tar.xz";
        url = "https://ftp.gnu.org/gnu/gmp/gmp-6.2.1.tar.xz";
        hash = "sha256-/UgpkSzd0S+EGBw0Ucx1K+IkZD6H+sSXtp7d2txJtPI=";
      }
      {
        name = "coreboot-crossgcc-mpfr-4.2.0.tar.xz";
        url = "https://ftp.gnu.org/gnu/mpfr/mpfr-4.2.0.tar.xz";
        hash = "sha256-BqN43xNQEkjBsttaqXeiyBJq6Emp2be+JUb7Spwm2ZM=";
      }
      {
        name = "coreboot-crossgcc-mpc-1.3.1.tar.gz";
        url = "https://ftp.gnu.org/gnu/mpc/mpc-1.3.1.tar.gz";
        hash = "sha256-q2QkkvXPiCt0qgy3MM1BCoHtzb7IlRg86TDnBsHHWbg=";
      }
      {
        name = "coreboot-crossgcc-gcc-11.3.0.tar.xz";
        url = "https://ftp.gnu.org/gnu/gcc/gcc-11.3.0/gcc-11.3.0.tar.xz";
        hash = "sha256-tHzygYaR9bHiHfK7OMeV+sLPvWQO3i0KXhyJ4zijrDk=";
      }
      {
        name = "coreboot-crossgcc-binutils-2.40.tar.xz";
        url = "https://ftp.gnu.org/gnu/binutils/binutils-2.40.tar.xz";
        hash = "sha256-D4pMJy1/F/Np3tEKSsoouOMEgo6VUm2kgrDMxN/J2OE=";
      }
      {
        name = "coreboot-crossgcc-R10_20_22.tar.gz";
        url = "https://github.com/acpica/acpica/archive/refs/tags/R10_20_22.tar.gz";
        hash = "sha256-GqF+sXec0XERAHTOJxplwGBG6su6e+fOXucd8bMcO4Y=";
      }
      {
        name = "coreboot-crossgcc-llvm-15.0.7.src.tar.xz";
        url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-15.0.7/llvm-15.0.7.src.tar.xz";
        hash = "sha256-StiyzIADyG0AeNFdmH2E46c58kqukDOGXAJ6uuk+56Q=";
      }
      {
        name = "coreboot-crossgcc-clang-15.0.7.src.tar.xz";
        url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-15.0.7/clang-15.0.7.src.tar.xz";
        hash = "sha256-prZz7xU3f7RgYtFk6N3E0Fw0j/iWjwFff0rwP1EAAGc=";
      }
      {
        name = "coreboot-crossgcc-cmake-15.0.7.src.tar.xz";
        url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-15.0.7/cmake-15.0.7.src.tar.xz";
        hash = "sha256-iYbym2NP2qmGLu3aeFE5af6XiDAcny2Tj0wQo+ej5+o=";
      }
      {
        name = "coreboot-crossgcc-compiler-rt-15.0.7.src.tar.xz";
        url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-15.0.7/compiler-rt-15.0.7.src.tar.xz";
        hash = "sha256-NTgyxmzOYJMeoEE7PAcfqtWe76cNAsl9qol4sV5LJbc=";
      }
      {
        name = "coreboot-crossgcc-clang-tools-extra-15.0.7.src.tar.xz";
        url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-15.0.7/clang-tools-extra-15.0.7.src.tar.xz";
        hash = "sha256-gJou9G1GvjuDyjiTVkBKwEH6bY9UlssC7DXSUq+2T9E=";
      }
      {
        name = "coreboot-crossgcc-cmake-3.26.3.tar.gz";
        url = "https://cmake.org/files/v3.26/cmake-3.26.3.tar.gz";
        hash = "sha256-u9jTkhdQnRY8tUSkDWQorGZt3IPiKQXT5SySV4Hw9lk=";
      }
      {
        name = "coreboot-crossgcc-nasm-2.15.05.tar.bz2";
        url = "https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/nasm-2.15.05.tar.bz2";
        hash = "sha256-PEuDOeWrVLG8sjFhAfiYWl2lCj+eUE1D+m81ZovuL9A=";
      }
    ];
    "coreboot-4.22.01" = [
      {
        name = "coreboot-crossgcc-gmp-6.3.0.tar.xz";
        url = "https://ftp.gnu.org/gnu/gmp/gmp-6.3.0.tar.xz";
        hash = "sha256-o8K4AgG4nmhhb0rTC8Zq7kknw85Q4zkpyoGdXENTiJg=";
      }
      {
        name = "coreboot-crossgcc-mpfr-4.2.1.tar.xz";
        url = "https://ftp.gnu.org/gnu/mpfr/mpfr-4.2.1.tar.xz";
        hash = "sha256-J3gHNTpnJpeJlpRa8T5Sgp46vXqaW3+yeTiU4Y8fy7I=";
      }
      {
        name = "coreboot-crossgcc-mpc-1.3.1.tar.gz";
        url = "https://ftp.gnu.org/gnu/mpc/mpc-1.3.1.tar.gz";
        hash = "sha256-q2QkkvXPiCt0qgy3MM1BCoHtzb7IlRg86TDnBsHHWbg=";
      }
      {
        name = "coreboot-crossgcc-gcc-11.4.0.tar.xz";
        url = "https://ftp.gnu.org/gnu/gcc/gcc-11.4.0/gcc-11.4.0.tar.xz";
        hash = "sha256-Py2yIrAH6KSiPNW6VnJu8I6LHx6yBV7nLBQCzqc6jdk=";
      }
      {
        name = "coreboot-crossgcc-binutils-2.41.tar.xz";
        url = "https://ftp.gnu.org/gnu/binutils/binutils-2.41.tar.xz";
        hash = "sha256-rppXieI0WeWWBuZxRyPy0//DHAMXQZHvDQFb3wYAdFA=";
      }
      {
        name = "coreboot-crossgcc-R06_28_23.tar.gz";
        url = "https://github.com/acpica/acpica/archive/refs/tags/R06_28_23.tar.gz";
        hash = "sha256-Ikh5m3ygincRrIfTGSQ1TtSQR1B2B9AzvTJ7qGHsTTE=";
      }
      {
        name = "coreboot-crossgcc-llvm-16.0.6.src.tar.xz";
        url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.6/llvm-16.0.6.src.tar.xz";
        hash = "sha256-6R20TRs7scM/zqmn0fJCO4g+qpFj09VsoqptLwcRvCk=";
      }
      {
        name = "coreboot-crossgcc-clang-16.0.6.src.tar.xz";
        url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.6/clang-16.0.6.src.tar.xz";
        hash = "sha256-EYa25u7+rdCZEu1zs3KehbWfBDckuygYqVouwCRXGEA=";
      }
      {
        name = "coreboot-crossgcc-cmake-16.0.6.src.tar.xz";
        url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.6/cmake-16.0.6.src.tar.xz";
        hash = "sha256-OdNCpBYQldLyj7ElPkWFl4rFBSERfaZm4rH28oti9RQ=";
      }
      {
        name = "coreboot-crossgcc-compiler-rt-16.0.6.src.tar.xz";
        url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.6/compiler-rt-16.0.6.src.tar.xz";
        hash = "sha256-eRGiqcyhA5Ohf2N8Aab1VVsKOPZP9H3JFoQTpBkLwts=";
      }
      {
        name = "coreboot-crossgcc-clang-tools-extra-16.0.6.src.tar.xz";
        url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.6/clang-tools-extra-16.0.6.src.tar.xz";
        hash = "sha256-F0x4RNslkLGLKlmpzlA/j+Q57cLeLw9iUAZQHJlzbzE=";
      }
      {
        name = "coreboot-crossgcc-cmake-3.26.4.tar.gz";
        url = "https://cmake.org/files/v3.26/cmake-3.26.4.tar.gz";
        hash = "sha256-MTtogMKRvU/jHAqlHW5iZZKCpSHmlfMNXMDSWrvVwgg=";
      }
      {
        name = "coreboot-crossgcc-nasm-2.16.01.tar.bz2";
        url = "https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/nasm-2.16.01.tar.bz2";
        hash = "sha256-NbatLuBI1BxHefBz8+/Kd2KoIrfS1O9OjfJM9ldHuy4=";
      }
    ];
  };
  musl-cross-make-deps = [
    {
      name = "config.sub";
      url = "https://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=3d5db9ebe860";
      hash = "sha256-ddXSVaKic7bmUfgu7Pq/bLzY6urnDoa0FzhMj0pY2NM=";
    }
    {
      name = "binutils-2.33.1.tar.xz";
      url = "https://ftp.gnu.org/gnu/binutils/binutils-2.33.1.tar.xz";
      hash = "sha256-q2b8LRw+wDWbjgiEPJ8ztj6HB+/f9eTMXCAOriRyLL8=";
    }
    {
      name = "gcc-9.4.0.tar.xz";
      url = "https://ftp.gnu.org/gnu/gcc/gcc-9.4.0/gcc-9.4.0.tar.xz";
      hash = "sha256-yV2jL0QDeNd1HdlVMxhvf8Bc60+2XrW4UjTmKZ65g44=";
    }
    {
      name = "gmp-6.1.2.tar.bz2";
      url = "https://ftp.gnu.org/gnu/gmp/gmp-6.1.2.tar.bz2";
      hash = "sha256-UnW7BPSGOhNRay85OSrF4nL14buAV7GK7Bybedc9j7I=";
    }
    {
      name = "linux-headers-4.19.88-2.tar.xz";
      url = "https://ftp.barfooze.de/pub/sabotage/tarballs//linux-headers-4.19.88-2.tar.xz";
      hash = "sha256-3Hq/c0SHVTZEJYo4Is/UKddGVnSeMJ8rJfCfQoLgVYg=";
    }
    {
      name = "mpc-1.1.0.tar.gz";
      url = "https://ftp.gnu.org/gnu/mpc/mpc-1.1.0.tar.gz";
      hash = "sha256-aYXFOBQ8EgjcsaxCztrW/1LiZ7R+X5cBg6PnUSW0PC4=";
    }
    {
      name = "mpfr-4.0.2.tar.bz2";
      url = "https://ftp.gnu.org/gnu/mpfr/mpfr-4.0.2.tar.bz2";
      hash = "sha256-wF4/AtCeDpAZOEzdWODxnGTm2x/W9ez3e0scYcolOsw=";
    }
    {
      name = "musl-1.2.5.tar.gz";
      url = "https://musl.libc.org/releases/musl-1.2.5.tar.gz";
      hash = "sha256-qaEYu+hNh2TaDqDSizqz+uhHf8fkCF2QECuFlvx8deQ=";
    }
  ];
}
